function piofrtos_make_rtw_hook(hookMethod, modelName, ~, ~, ~, ~, buildInfo)
%PIOFRTOS_MAKE_RTW_HOOK - Build-process hook for the PlatformIO FreeRTOS target.
%   Dispatches on hookMethod string. On entry, validates the model and locates
%   PlatformIO unless GenCodeOnly is on. After TLC and before make, writes
%   generated PlatformIO files via piofrtos.writeGeneratedFiles. Prints messages
%   on error and exit. Unknown future hook stages are ignored. buildInfo may be
%   empty when fewer than seven arguments are supplied.
%
%   Syntax:
%       piofrtos_make_rtw_hook(hookMethod, modelName, rtwroot, templateMakefile, ...
%           buildOpts, buildArgs, buildInfo)
%
%   Inputs:
%       hookMethod - Stage name (entry, before_tlc, after_tlc, before_make, ...)
%       modelName  - Model being built
%       buildInfo  - Optional RTW build info (default [] if omitted)
%
%   Outputs:
%       none
%
%   Example:
%       % Invoked automatically by the piofrtos.tlc make process
%
%   Other m-files required: piofrtos.validateModelForTarget,
%       piofrtos.locatePlatformio, piofrtos.writeGeneratedFiles
%   Subfunctions: none
%   MAT-files required: none
%
%   See also: SETUP_PIOFRTOS, BUILD_ALL

%   Author: Frey, Jed
%   28-Sep-2026; Last revision: 28-Sep-2026

%------------- BEGIN CODE --------------

    if nargin < 7
        buildInfo = [];
    end

    modelName = string(modelName);

    switch string(hookMethod)
        case "error"
            fprintf("Arduino FreeRTOS (PlatformIO) build failed for %s.\n", modelName);
        case "entry"
            piofrtos.validateModelForTarget(modelName);
            generateCodeOnly = false;
            try
                generateCodeOnly = string(get_param(modelName, "GenCodeOnly")) == "on";
            catch
                % GenCodeOnly is unavailable until the code-generation component is attached.
            end
            piofrtos.locatePlatformio(MustExist=~generateCodeOnly);
        case "before_tlc"
            % TLC input is generated by Embedded Coder; no extra files yet.
        case "after_tlc"
            piofrtos.writeGeneratedFiles(modelName, buildInfo);
        case "before_make"
            piofrtos.writeGeneratedFiles(modelName, buildInfo);
        case "after_make"
            % PlatformIO already compiled and optionally uploaded the firmware.
        case "exit"
            fprintf("Arduino FreeRTOS (PlatformIO) build finished for %s.\n", modelName);
        otherwise
            % Ignore unknown hook stages from future MATLAB releases.
    end
end
