function piofrtos_make_rtw_hook(hookMethod, modelName, ~, ~, ~, ~, buildInfo)
%piofrtos_make_rtw_hook Build-process hook for the PlatformIO FreeRTOS target.
    if nargin < 7
        buildInfo = [];
    end

    modelName = string(modelName);

    switch string(hookMethod)
        case "error"
            fprintf("Arduino FreeRTOS (PlatformIO) build failed for %s.\n", modelName);
        case "entry"
            piofrtos.validateModelForTarget(modelName);
            generateCodeOnly = false;
            try
                generateCodeOnly = string(get_param(modelName, "GenCodeOnly")) == "on";
            catch
                % GenCodeOnly is unavailable until the code-generation component is attached.
            end
            piofrtos.locatePlatformio(MustExist=~generateCodeOnly);
        case "before_tlc"
            % TLC input is generated by Embedded Coder; no extra files yet.
        case "after_tlc"
            piofrtos.writeGeneratedFiles(modelName, buildInfo);
        case "before_make"
            piofrtos.writeGeneratedFiles(modelName, buildInfo);
        case "after_make"
            % PlatformIO already compiled and optionally uploaded the firmware.
        case "exit"
            fprintf("Arduino FreeRTOS (PlatformIO) build finished for %s.\n", modelName);
        otherwise
            % Ignore unknown hook stages from future MATLAB releases.
    end
end
