/* Generated by the Arduino FreeRTOS (PlatformIO) Simulink target. */
/* One FreeRTOS task is created for each discrete sample rate. */
/* Includes the generated model uno_blink. */

#include <Arduino.h>

#if __has_include("Arduino_FreeRTOS.h")
#include "Arduino_FreeRTOS.h"
#elif defined(ARDUINO_ARCH_ESP32)
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#else
#include "FreeRTOS.h"
#include "task.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif
#include "uno_blink.h"
#ifdef __cplusplus
}
#endif

#ifndef PIOFRTOS_TASK_STACK
#define PIOFRTOS_TASK_STACK 192
#endif

static void piofrtosTask_rate0(void *taskParameter)
{
    (void)taskParameter;
    const TickType_t periodTicks = pdMS_TO_TICKS(100);
    TickType_t lastWakeTick = xTaskGetTickCount();

    for (;;)
    {
        uno_blink_step();
        vTaskDelayUntil(&lastWakeTick, periodTicks);
    }
}

void setup()
{
    Serial.begin(115200);
    uno_blink_initialize();

    xTaskCreate(
        piofrtosTask_rate0,
        "rate0",
        PIOFRTOS_TASK_STACK,
        NULL,
        tskIDLE_PRIORITY + 1,
        NULL);

#if !defined(ARDUINO_ARCH_ESP32)
    vTaskStartScheduler();
#endif
}

void loop()
{
#if defined(ARDUINO_ARCH_ESP32)
    vTaskDelay(pdMS_TO_TICKS(1000));
#endif
}
