# Generated by piofrtos.generateTargetFiles. Do not edit by hand.
#
# Template makefile for the Arduino FreeRTOS (PlatformIO) target.
# make_rtw expands tokens and then invokes MATLAB gmake, which calls
# the host-installed PlatformIO CLI.

#------------------------ Macros read by make_rtw ------------------------------
#
# MAKECMD         - Command used to invoke the make utility
# HOST            - PC or UNIX
# BUILD           - Invoke make from the build procedure (yes/no)
# SYS_TARGET_FILE - Name of system target file

MAKECMD         = "C:\Program Files\MATLAB\R2025b\bin/win64/gmake"
HOST            = PC
BUILD           = yes
SYS_TARGET_FILE = piofrtos.tlc
BUILD_SUCCESS   = ### Created

#---------------------- Tokens expanded by make_rtw ----------------------------

MODEL                   = uno_blink
MODULES                 = 
MAKEFILE                = uno_blink.mk
MATLAB_ROOT             = C:\Program Files\MATLAB\R2025b
ALT_MATLAB_ROOT         = C:\PROGRA~1\MATLAB\R2025b
START_DIR               = C:\projects\Simulink-Arduino-FreeRTOS-PIO\examples
NUMST                   = 1
NCSTATES                = 0
COMPUTER                = PCWIN64
BUILDARGS               =  GENERATE_ERT_S_FUNCTION=0 INCLUDE_MDL_TERMINATE_FCN=1 COMBINE_OUTPUT_UPDATE_FCNS=1 MAT_FILE=0 MULTI_INSTANCE_CODE=0 INTEGER_CODE=0 GENERATE_ASAP2=0 EXT_MODE=0 EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0 TMW_EXTMODE_TESTING=0 PIO_EXTRA_LIBRARIES="feilipu/FreeRTOS" OPTS="-DTID01EQ=0"
MULTITASKING            = 0
PRODUCT                 = $(RELATIVE_PATH_TO_ANCHOR)\uno_blink.exe
MODELREF_TARGET_TYPE    = NONE
RELATIVE_PATH_TO_ANCHOR = ..
DEFINES_CUSTOM          = 
DEFINES_OTHER           = -DHAVESTDIO
COMPILE_FLAGS_OTHER     = 
MODEL_HAS_DYNAMICALLY_LOADED_SFCNS = 0

PIO_PLATFORM            = atmelavr
PIO_BOARD               = Arduino Uno
PIO_FRAMEWORK           = arduino
PIO_MONITOR_SPEED       = 115200
PIO_UPLOAD              = 0
PIO_TASK_STACK_WORDS    = 192

-include pio_cmd.mk
PIO_CMD ?= pio

ifeq ($(MODELREF_TARGET_TYPE),NONE)

ifeq ($(PIO_UPLOAD),1)
ALL_GOAL = firmware upload
else
ifeq ($(PIO_UPLOAD),on)
ALL_GOAL = firmware upload
else
ALL_GOAL = firmware
endif
endif

.PHONY: all firmware upload

all: $(ALL_GOAL)

firmware:
	"$(PIO_CMD)" run --project-dir .
	@echo ### Created PlatformIO firmware for $(MODEL)

upload:
	"$(PIO_CMD)" run --project-dir . -t upload
	@echo ### Uploaded PlatformIO firmware for $(MODEL)

else

.PHONY: all

all:
	@echo ### Skipping PlatformIO for referenced model $(MODEL)

endif
