function filePath = emitPlatformioIni(filePath, options)
%emitPlatformioIni Write a PlatformIO project file for generated ERT code.
    arguments
        filePath (1,1) string
        options.ModelName (1,1) string
        options.Platform (1,1) string = "atmelavr"
        options.Board (1,1) string = "uno"
        options.Framework (1,1) string = "arduino"
        options.ExtraLibraries (1,1) string = ""
        options.MonitorSpeed (1,1) string = "115200"
        options.IncludeFlags (1,:) string = "-I."
        options.Defines (1,:) string = string.empty(1, 0)
    end

    [knownTarget, isKnown] = piofrtos.resolveKnownTarget(options.Board);
    if isKnown
        options.Board = knownTarget.Board;
        if strlength(strip(options.Platform)) == 0
            options.Platform = knownTarget.Platform;
        end
        if strlength(strip(options.Framework)) == 0
            options.Framework = knownTarget.Framework;
        end
    end

    envName = sanitizeEnvName(options.Board);
    libraryLines = piofrtos.normalizeLibraries(options.ExtraLibraries);
    includeFlags = unique(options.IncludeFlags, "stable");
    includeFlags = includeFlags(strlength(strip(includeFlags)) > 0);

    lines = [
        "; Generated by the Arduino FreeRTOS (PlatformIO) Simulink target."
        "; Model: " + options.ModelName
        ""
        "[platformio]"
        "src_dir = ."
        "include_dir = ."
        ""
        "[env:" + envName + "]"
        "platform = " + options.Platform
        "board = " + options.Board
        "framework = " + options.Framework
        "monitor_speed = " + options.MonitorSpeed
        "build_src_filter ="
        "    +<*>"
        "    -<ert_main.c>"
        "    -<ert_main.cpp>"
        "    -<rt_main.c>"
        "    -<rt_main.cpp>"
        "    -<rt_malloc_main.c>"
        "    -<rt_malloc_main.cpp>"
        "    -<piofrtos_main.cpp>"
        "build_flags ="
        ];

    defineFlags = "-DMODEL=" + options.ModelName;
    if ~isempty(options.Defines)
        defineFlags = [defineFlags, options.Defines];
    end

    for flagIndex = 1:numel(includeFlags)
        lines(end+1) = "    " + includeFlags(flagIndex); %#ok<AGROW>
    end
    for defineIndex = 1:numel(defineFlags)
        lines(end+1) = "    " + defineFlags(defineIndex); %#ok<AGROW>
    end

    if ~isempty(libraryLines)
        lines(end+1) = "lib_deps =";
        for libraryIndex = 1:numel(libraryLines)
            lines(end+1) = "    " + libraryLines(libraryIndex); %#ok<AGROW>
        end
    end

    writelines(lines, filePath);
end

function envName = sanitizeEnvName(board)
    envName = regexprep(char(board), "[^A-Za-z0-9_]", "_");
    if isempty(envName)
        envName = "board";
    end
    envName = string(envName);
end
