function filePath = emitFreeRtosMain(filePath, modelName, rates, options)
%EMITFREERTOSMAIN - Write an Arduino FreeRTOS main with one task per sample rate.
%   Emits main.cpp for the piofrtos PlatformIO FreeRTOS Simulink target. Each
%   rates entry becomes a static task that calls StepFunction then
%   vTaskDelayUntil. setup() runs Serial.begin, InitFunction, and xTaskCreate
%   with priority from rates.Priority and stack PIOFRTOS_TASK_STACK (from
%   StackWords). Errors with piofrtos:NoRatesForMain when rates is empty.
%   Includes Arduino_FreeRTOS.h, ESP32 freertos headers, or FreeRTOS.h/task.h.
%
%   Syntax:
%       filePath = piofrtos.emitFreeRtosMain(filePath, modelName, rates)
%       filePath = piofrtos.emitFreeRtosMain(filePath, modelName, rates, ...
%           HeaderFile=h, InitFunction=init, StackWords="2048", ...
%           MonitorSpeed="115200")
%
%   Inputs:
%       filePath - (1,1) string destination path (typically main.cpp).
%       modelName - (1,1) string model name used in comments and header fallback.
%       rates - struct array with PeriodSeconds, StepFunction, Priority, TaskName
%           (and related fields from getModelSampleRates). Must be non-empty.
%       options.HeaderFile - (1,1) string. Default: modelName + ".h".
%       options.InitFunction - (1,1) string. Default: modelName + "_initialize".
%       options.StackWords - (1,1) string stack depth words. Default: "2048".
%           Rounded with max(1, round(double(...))).
%       options.MonitorSpeed - (1,1) string baud for Serial.begin. Default: "115200".
%
%   Outputs:
%       filePath - same path after writelines completes.
%
%   Example:
%       % Write FreeRTOS main using rates from getModelSampleRates.
%       rates = piofrtos.getModelSampleRates("blink");
%       piofrtos.emitFreeRtosMain("main.cpp", "blink", rates);
%
%   Other m-files required: none
%   Subfunctions: periodToTicksExpr, modelHeaderFile, quoteCString
%   MAT-files required: none
%
%   See also: GETMODELSAMPLERATES, WRITEGENERATEDFILES, EMITPLATFORMIOINI

%   Author: Frey, Jed
%   28-Sep-2026; Last revision: 28-Sep-2026

%------------- BEGIN CODE --------------
    arguments
        filePath (1,1) string
        modelName (1,1) string
        rates struct
        options.HeaderFile (1,1) string = modelName + ".h"
        options.InitFunction (1,1) string = modelName + "_initialize"
        options.StackWords (1,1) string = "2048"
        options.MonitorSpeed (1,1) string = "115200"
    end

    rates = rates(:);

    if isempty(rates)
        error("piofrtos:NoRatesForMain", ...
            "Cannot emit FreeRTOS main for %s because no discrete rates were provided.", ...
            modelName);
    end

    stackWords = max(1, round(double(options.StackWords)));
    monitorSpeed = max(1, round(double(options.MonitorSpeed)));
    headerFile = modelHeaderFile(modelName, options.HeaderFile);

    lines = [
        "/* Generated by the Arduino FreeRTOS (PlatformIO) Simulink target. */"
        "/* One FreeRTOS task is created for each discrete sample rate. */"
        "/* Includes the generated model " + modelName + ". */"
        ""
        "#include <Arduino.h>"
        ""
        "#if __has_include(""Arduino_FreeRTOS.h"")"
        "#include ""Arduino_FreeRTOS.h"""
        "#elif defined(ARDUINO_ARCH_ESP32)"
        "#include ""freertos/FreeRTOS.h"""
        "#include ""freertos/task.h"""
        "#else"
        "#include ""FreeRTOS.h"""
        "#include ""task.h"""
        "#endif"
        ""
        "#ifdef __cplusplus"
        "extern ""C"" {"
        "#endif"
        "#include " + quoteCString(headerFile)
        "#ifdef __cplusplus"
        "}"
        "#endif"
        ""
        "#ifndef PIOFRTOS_TASK_STACK"
        "#define PIOFRTOS_TASK_STACK " + string(stackWords)
        "#endif"
        ""
        ];

    for rateIndex = 1:numel(rates)
        rate = rates(rateIndex);
        [ticksExpr, minTickHz] = periodToTicksExpr(rate.PeriodSeconds);
        taskFunction = "piofrtosTask_" + rate.TaskName;

        if ~isempty(minTickHz)
            lines = [lines; ...
                "#if configTICK_RATE_HZ < " + string(minTickHz)
                "#error Sample rate " + string(rate.PeriodSeconds) + ...
                " s is faster than configTICK_RATE_HZ. Increase the tick rate or slow the model."
                "#endif"
                ]; %#ok<AGROW>
        end

        lines = [lines; ...
            "static void " + taskFunction + "(void *taskParameter)"
            "{"
            "    (void)taskParameter;"
            "    const TickType_t periodTicks = " + ticksExpr + ";"
            "    TickType_t lastWakeTick = xTaskGetTickCount();"
            ""
            "    for (;;)"
            "    {"
            "        " + string(rate.StepFunction) + "();"
            "        vTaskDelayUntil(&lastWakeTick, periodTicks);"
            "    }"
            "}"
            ""
            ]; %#ok<AGROW>
    end

    lines = [lines;
        "void setup()"
        "{"
        "    Serial.begin(" + string(monitorSpeed) + ");"
        "    " + options.InitFunction + "();"
        ""
        ];

    for rateIndex = 1:numel(rates)
        rate = rates(rateIndex);
        taskFunction = "piofrtosTask_" + rate.TaskName;
        taskName = quoteCString(rate.TaskName);
        lines = [lines; ...
            "    xTaskCreate("
            "        " + taskFunction + ","
            "        " + taskName + ","
            "        PIOFRTOS_TASK_STACK,"
            "        NULL,"
            "        tskIDLE_PRIORITY + " + string(rate.Priority) + ","
            "        NULL);"
            ]; %#ok<AGROW>
    end

    lines = [lines;
        ""
        "#if !defined(ARDUINO_ARCH_ESP32)"
        "    vTaskStartScheduler();"
        "#endif"
        "}"
        ""
        "void loop()"
        "{"
        "#if defined(ARDUINO_ARCH_ESP32)"
        "    vTaskDelay(pdMS_TO_TICKS(1000));"
        "#endif"
        "}"
        ];

    writelines(lines, filePath);
end

function [ticksExpr, minTickHz] = periodToTicksExpr(periodSeconds)
%PERIODTOTICKSEXPR - Convert a sample period to a FreeRTOS tick expression.
%   Local helper for emitFreeRtosMain. Whole-millisecond periods use
%   pdMS_TO_TICKS(N) with empty minTickHz. Otherwise emits a float multiply by
%   configTICK_RATE_HZ and sets minTickHz to ceil(1/periodSeconds) for #error
%   guards when the tick rate is too low.
%
%   Syntax:
%       [ticksExpr, minTickHz] = periodToTicksExpr(periodSeconds)
%
%   Inputs:
%       periodSeconds - numeric sample period in seconds (from rates.PeriodSeconds).
%
%   Outputs:
%       ticksExpr - string C expression assigning TickType_t periodTicks.
%       minTickHz - empty when using pdMS_TO_TICKS; otherwise required tick Hz.
%
%   Example:
%       [ticksExpr, minTickHz] = periodToTicksExpr(0.01);
%
%   See also: EMITFREERTOSMAIN
    milliseconds = periodSeconds * 1000;
    roundedMilliseconds = round(milliseconds);
    if abs(milliseconds - roundedMilliseconds) < 1e-8 && roundedMilliseconds >= 1
        ticksExpr = "pdMS_TO_TICKS(" + string(roundedMilliseconds) + ")";
        minTickHz = [];
        return
    end

    minTickHz = ceil(1 / periodSeconds);
    ticksExpr = "(TickType_t)((" + sprintf("%.17g", periodSeconds) + ") * configTICK_RATE_HZ)";
    ticksExpr = string(ticksExpr);
end

function headerFile = modelHeaderFile(modelName, headerFile)
%MODELHEADERFILE - Normalize the generated model header base name for #include.
%   Local helper for emitFreeRtosMain. Empty headerFile becomes modelName.h.
%   Strips directories so only base + extension are included; missing extension
%   defaults to ".h".
%
%   Syntax:
%       headerFile = modelHeaderFile(modelName, headerFile)
%
%   Inputs:
%       modelName - string model name used when the header is empty or baseless.
%       headerFile - string path or file name from code descriptor or default.
%
%   Outputs:
%       headerFile - string "basename.ext" suitable for quoteCString.
%
%   Example:
%       headerFile = modelHeaderFile("blink", "blink.h");
%
%   See also: EMITFREERTOSMAIN, QUOTECSTRING
    headerFile = strip(string(headerFile));
    if strlength(headerFile) == 0
        headerFile = modelName + ".h";
    end

    [~, headerBase, headerExt] = fileparts(headerFile);
    if strlength(headerBase) == 0
        headerBase = modelName;
    end
    if strlength(headerExt) == 0
        headerExt = ".h";
    end
    headerFile = headerBase + headerExt;
end

function quoted = quoteCString(value)
%QUOTECSTRING - Wrap a string in C double quotes for generated source.
%   Local helper for emitFreeRtosMain (includes and xTaskCreate task names).
%
%   Syntax:
%       quoted = quoteCString(value)
%
%   Inputs:
%       value - string or convertible value placed between double quotes.
%
%   Outputs:
%       quoted - string like """name""".
%
%   Example:
%       quoted = quoteCString("blink.h");
%
%   See also: EMITFREERTOSMAIN, MODELHEADERFILE
    quoted = """" + string(value) + """";
end
