function filePath = emitFreeRtosMain(filePath, modelName, rates, options)
%emitFreeRtosMain Write an Arduino FreeRTOS main with one task per sample rate.
    arguments
        filePath (1,1) string
        modelName (1,1) string
        rates struct
        options.HeaderFile (1,1) string = modelName + ".h"
        options.InitFunction (1,1) string = modelName + "_initialize"
        options.StackWords (1,1) string = "2048"
        options.MonitorSpeed (1,1) string = "115200"
    end

    rates = rates(:);

    if isempty(rates)
        error("piofrtos:NoRatesForMain", ...
            "Cannot emit FreeRTOS main for %s because no discrete rates were provided.", ...
            modelName);
    end

    stackWords = max(1, round(double(options.StackWords)));
    monitorSpeed = max(1, round(double(options.MonitorSpeed)));
    headerFile = modelHeaderFile(modelName, options.HeaderFile);

    lines = [
        "/* Generated by the Arduino FreeRTOS (PlatformIO) Simulink target. */"
        "/* One FreeRTOS task is created for each discrete sample rate. */"
        "/* Includes the generated model " + modelName + ". */"
        ""
        "#include <Arduino.h>"
        ""
        "#if __has_include(""Arduino_FreeRTOS.h"")"
        "#include ""Arduino_FreeRTOS.h"""
        "#elif defined(ARDUINO_ARCH_ESP32)"
        "#include ""freertos/FreeRTOS.h"""
        "#include ""freertos/task.h"""
        "#else"
        "#include ""FreeRTOS.h"""
        "#include ""task.h"""
        "#endif"
        ""
        "#ifdef __cplusplus"
        "extern ""C"" {"
        "#endif"
        "#include " + quoteCString(headerFile)
        "#ifdef __cplusplus"
        "}"
        "#endif"
        ""
        "#ifndef PIOFRTOS_TASK_STACK"
        "#define PIOFRTOS_TASK_STACK " + string(stackWords)
        "#endif"
        ""
        ];

    for rateIndex = 1:numel(rates)
        rate = rates(rateIndex);
        [ticksExpr, minTickHz] = periodToTicksExpr(rate.PeriodSeconds);
        taskFunction = "piofrtosTask_" + rate.TaskName;

        if ~isempty(minTickHz)
            lines = [lines; ...
                "#if configTICK_RATE_HZ < " + string(minTickHz)
                "#error Sample rate " + string(rate.PeriodSeconds) + ...
                " s is faster than configTICK_RATE_HZ. Increase the tick rate or slow the model."
                "#endif"
                ]; %#ok<AGROW>
        end

        lines = [lines; ...
            "static void " + taskFunction + "(void *taskParameter)"
            "{"
            "    (void)taskParameter;"
            "    const TickType_t periodTicks = " + ticksExpr + ";"
            "    TickType_t lastWakeTick = xTaskGetTickCount();"
            ""
            "    for (;;)"
            "    {"
            "        " + string(rate.StepFunction) + "();"
            "        vTaskDelayUntil(&lastWakeTick, periodTicks);"
            "    }"
            "}"
            ""
            ]; %#ok<AGROW>
    end

    lines = [lines;
        "void setup()"
        "{"
        "    Serial.begin(" + string(monitorSpeed) + ");"
        "    " + options.InitFunction + "();"
        ""
        ];

    for rateIndex = 1:numel(rates)
        rate = rates(rateIndex);
        taskFunction = "piofrtosTask_" + rate.TaskName;
        taskName = quoteCString(rate.TaskName);
        lines = [lines; ...
            "    xTaskCreate("
            "        " + taskFunction + ","
            "        " + taskName + ","
            "        PIOFRTOS_TASK_STACK,"
            "        NULL,"
            "        tskIDLE_PRIORITY + " + string(rate.Priority) + ","
            "        NULL);"
            ]; %#ok<AGROW>
    end

    lines = [lines;
        ""
        "#if !defined(ARDUINO_ARCH_ESP32)"
        "    vTaskStartScheduler();"
        "#endif"
        "}"
        ""
        "void loop()"
        "{"
        "#if defined(ARDUINO_ARCH_ESP32)"
        "    vTaskDelay(pdMS_TO_TICKS(1000));"
        "#endif"
        "}"
        ];

    writelines(lines, filePath);
end

function [ticksExpr, minTickHz] = periodToTicksExpr(periodSeconds)
    milliseconds = periodSeconds * 1000;
    roundedMilliseconds = round(milliseconds);
    if abs(milliseconds - roundedMilliseconds) < 1e-8 && roundedMilliseconds >= 1
        ticksExpr = "pdMS_TO_TICKS(" + string(roundedMilliseconds) + ")";
        minTickHz = [];
        return
    end

    minTickHz = ceil(1 / periodSeconds);
    ticksExpr = "(TickType_t)((" + sprintf("%.17g", periodSeconds) + ") * configTICK_RATE_HZ)";
    ticksExpr = string(ticksExpr);
end

function headerFile = modelHeaderFile(modelName, headerFile)
    headerFile = strip(string(headerFile));
    if strlength(headerFile) == 0
        headerFile = modelName + ".h";
    end

    [~, headerBase, headerExt] = fileparts(headerFile);
    if strlength(headerBase) == 0
        headerBase = modelName;
    end
    if strlength(headerExt) == 0
        headerExt = ".h";
    end
    headerFile = headerBase + headerExt;
end

function quoted = quoteCString(value)
    quoted = """" + string(value) + """";
end
