function generatedFiles = generateTargetFiles(targetFolder)
%generateTargetFiles Write the system target file and template makefile.
%   generatedFiles = piofrtos.generateTargetFiles() writes piofrtos.tlc and
%   piofrtos.tmf into the target folder. Option names, defaults, and make
%   tokens come from piofrtos.getOptionTable so the two files stay aligned.
    arguments
        targetFolder (1,1) string = piofrtos.getTargetFolder()
    end

    if ~isfolder(targetFolder)
        mkdir(targetFolder);
    end

    tlcPath = fullfile(targetFolder, "piofrtos.tlc");
    tmfPath = fullfile(targetFolder, "piofrtos.tmf");
    writelines(buildSystemTargetFile(), tlcPath);
    writelines(buildTemplateMakefile(), tmfPath);

    generatedFiles = [tlcPath; tmfPath];
end

function lines = buildSystemTargetFile()
    optionTable = piofrtos.getOptionTable();
    lines = [
        "%% SYSTLC: Arduino FreeRTOS (PlatformIO) TMF: piofrtos.tmf MAKE: make_rtw"
        "%%"
        "%% Generated by piofrtos.generateTargetFiles. Do not edit by hand."
        "%% Abstract: Embedded Coder target that builds with host-installed PlatformIO"
        "%%           and maps each discrete sample rate to a FreeRTOS task."
        "%selectfile NULL_FILE"
        ""
        "%assign CodeFormat = ""Embedded-C"""
        "%assign TargetType = ""RT"""
        "%assign Language   = ""C"""
        "%assign PreCodeGenExecCompliant = 1"
        "%assign RateBasedStepFcn = 1"
        "%assign SuppressSetEventsForThisBaseRateFcn = 1"
        "%assign SuppressMultiTaskScheduler = 1"
        "%assign AutoBuildProcedure = TLC_FALSE"
        ""
        "%include ""codegenentry.tlc"""
        ""
        "/%"
        "  BEGIN_RTW_OPTIONS"
        ""
        "  oIdx = 1;"
        "  rtwoptions(oIdx).prompt         = 'PlatformIO';"
        "  rtwoptions(oIdx).type           = 'Category';"
        "  rtwoptions(oIdx).enable         = 'on';"
        string(sprintf("  rtwoptions(oIdx).default        = %d;", numel(optionTable)))
        "  rtwoptions(oIdx).popupstrings   = '';"
        "  rtwoptions(oIdx).tlcvariable    = '';"
        "  rtwoptions(oIdx).tooltip        = '';"
        "  rtwoptions(oIdx).callback       = '';"
        "  rtwoptions(oIdx).opencallback   = '';"
        "  rtwoptions(oIdx).closecallback  = '';"
        "  rtwoptions(oIdx).makevariable   = '';"
        ""
        ];

    for optionIndex = 1:numel(optionTable)
        option = optionTable(optionIndex);
        lines = [lines; buildRtwOptionBlock(option)]; %#ok<AGROW>
    end

    lines = [lines;
        "  rtwgensettings.BuildDirSuffix = '_piofrtos_rtw';"
        "  rtwgensettings.Version        = '1';"
        "  rtwgensettings.DerivedFrom    = 'ert.tlc';"
        "  rtwgensettings.SelectCallback = 'piofrtos.selectCallback(hDlg, hSrc)';"
        ""
        "  END_RTW_OPTIONS"
        "%/"
        ];
end

function lines = buildRtwOptionBlock(option)
    tooltipLiteral = toMatlabSingleQuoted(option.Tooltip);
    defaultLiteral = toMatlabSingleQuoted(option.Default);
    popupLiteral = toMatlabSingleQuoted(getOptionField(option, "PopupStrings", ""));
    callbackLiteral = toMatlabSingleQuoted(getOptionField(option, "Callback", ""));

    lines = [
        "  oIdx = oIdx + 1;"
        string(sprintf("  rtwoptions(oIdx).prompt         = '%s';", option.Prompt))
        string(sprintf("  rtwoptions(oIdx).type           = '%s';", option.Type))
        "  rtwoptions(oIdx).enable         = 'on';"
        string(sprintf("  rtwoptions(oIdx).default        = %s;", defaultLiteral))
        string(sprintf("  rtwoptions(oIdx).popupstrings   = %s;", popupLiteral))
        string(sprintf("  rtwoptions(oIdx).tlcvariable    = '%s';", option.TlcVariable))
        string(sprintf("  rtwoptions(oIdx).makevariable   = '%s';", option.MakeVariable))
        string(sprintf("  rtwoptions(oIdx).tooltip        = %s;", tooltipLiteral))
        string(sprintf("  rtwoptions(oIdx).callback       = %s;", callbackLiteral))
        ""
        ];
end

function value = getOptionField(option, fieldName, defaultValue)
    if isfield(option, fieldName)
        value = option.(fieldName);
    else
        value = defaultValue;
    end
end

function literal = toMatlabSingleQuoted(value)
    escaped = replace(string(value), "'", "''");
    literal = "'" + escaped + "'";
end

function lines = buildTemplateMakefile()
    lines = [
        "# Generated by piofrtos.generateTargetFiles. Do not edit by hand."
        "#"
        "# Template makefile for the Arduino FreeRTOS (PlatformIO) target."
        "# make_rtw expands tokens and then invokes MATLAB gmake, which calls"
        "# the host-installed PlatformIO CLI."
        ""
        "#------------------------ Macros read by make_rtw ------------------------------"
        "#"
        "# MAKECMD         - Command used to invoke the make utility"
        "# HOST            - PC or UNIX"
        "# BUILD           - Invoke make from the build procedure (yes/no)"
        "# SYS_TARGET_FILE - Name of system target file"
        ""
        "MAKECMD         = ""|>MATLAB_BIN<|/|>ARCH<|/gmake"""
        "HOST            = PC"
        "BUILD           = yes"
        "SYS_TARGET_FILE = piofrtos.tlc"
        "BUILD_SUCCESS   = ### Created"
        ""
        "#---------------------- Tokens expanded by make_rtw ----------------------------"
        ""
        "MODEL                   = |>MODEL_NAME<|"
        "MODULES                 = |>MODEL_MODULES<|"
        "MAKEFILE                = |>MAKEFILE_NAME<|"
        "MATLAB_ROOT             = |>MATLAB_ROOT<|"
        "ALT_MATLAB_ROOT         = |>ALT_MATLAB_ROOT<|"
        "START_DIR               = |>START_DIR<|"
        "NUMST                   = |>NUMST<|"
        "NCSTATES                = |>NCSTATES<|"
        "COMPUTER                = |>COMPUTER<|"
        "BUILDARGS               = |>BUILDARGS<|"
        "MULTITASKING            = |>MULTITASKING<|"
        "PRODUCT                 = |>PRODUCT<|"
        "MODELREF_TARGET_TYPE    = |>MODELREF_TARGET_TYPE<|"
        "RELATIVE_PATH_TO_ANCHOR = |>RELATIVE_PATH_TO_ANCHOR<|"
        "DEFINES_CUSTOM          = |>DEFINES_CUSTOM<|"
        "DEFINES_OTHER           = |>DEFINES_OTHER<|"
        "COMPILE_FLAGS_OTHER     = |>COMPILE_FLAGS_OTHER<|"
        "MODEL_HAS_DYNAMICALLY_LOADED_SFCNS = |>MODEL_HAS_DYNAMICALLY_LOADED_SFCNS<|"
        ""
        "PIO_PLATFORM            = |>PIO_PLATFORM<|"
        "PIO_BOARD               = |>PIO_BOARD<|"
        "PIO_FRAMEWORK           = |>PIO_FRAMEWORK<|"
        "PIO_MONITOR_SPEED       = |>PIO_MONITOR_SPEED<|"
        "PIO_UPLOAD              = |>PIO_UPLOAD<|"
        "PIO_TASK_STACK_WORDS    = |>PIO_TASK_STACK_WORDS<|"
        ""
        "-include pio_cmd.mk"
        "PIO_CMD ?= pio"
        ""
        "ifeq ($(MODELREF_TARGET_TYPE),NONE)"
        ""
        "ifeq ($(PIO_UPLOAD),1)"
        "ALL_GOAL = firmware upload"
        "else"
        "ifeq ($(PIO_UPLOAD),on)"
        "ALL_GOAL = firmware upload"
        "else"
        "ALL_GOAL = firmware"
        "endif"
        "endif"
        ""
        ".PHONY: all firmware upload"
        ""
        "all: $(ALL_GOAL)"
        ""
        "firmware:"
        string(sprintf("\t""$(PIO_CMD)"" run --project-dir ."))
        string(sprintf("\t@echo ### Created PlatformIO firmware for $(MODEL)"))
        ""
        "upload:"
        string(sprintf("\t""$(PIO_CMD)"" run --project-dir . -t upload"))
        string(sprintf("\t@echo ### Uploaded PlatformIO firmware for $(MODEL)"))
        ""
        "else"
        ""
        ".PHONY: all"
        ""
        "all:"
        string(sprintf("\t@echo ### Skipping PlatformIO for referenced model $(MODEL)"))
        ""
        "endif"
        ];
end
