function generatedFiles = generateTargetFiles(targetFolder)
%GENERATETARGETFILES - Write the system target file and template makefile.
%   Regenerates piofrtos.tlc and piofrtos.tmf for the Arduino FreeRTOS
%   (PlatformIO) Simulink target. Option names, defaults, tooltips, callbacks,
%   and make tokens come from getOptionTable so TLC rtwoptions and TMF macros
%   stay aligned. Creates targetFolder if needed. Default folder is
%   getTargetFolder(). Overwrites both files via writelines; do not edit them
%   by hand after generation.
%
%   Syntax:
%       generatedFiles = piofrtos.generateTargetFiles()
%       generatedFiles = piofrtos.generateTargetFiles(targetFolder)
%
%   Inputs:
%       targetFolder - (1,1) string output directory. Default:
%           piofrtos.getTargetFolder(). Created with mkdir when missing.
%
%   Outputs:
%       generatedFiles - 2x1 string column [tlcPath; tmfPath] for piofrtos.tlc
%           and piofrtos.tmf under targetFolder.
%
%   Example:
%       % Refresh STF/TMF in the package target folder.
%       generatedFiles = piofrtos.generateTargetFiles();
%
%   Other m-files required: getOptionTable, getTargetFolder
%   Subfunctions: buildSystemTargetFile, buildRtwOptionBlock, getOptionField, ...
%       toMatlabSingleQuoted, buildTemplateMakefile
%   MAT-files required: none
%
%   See also: GETOPTIONTABLE, CONFIGUREMODEL, SELECTCALLBACK

%   Author: Frey, Jed
%   28-Sep-2026; Last revision: 28-Sep-2026

%------------- BEGIN CODE --------------
    arguments
        targetFolder (1,1) string = piofrtos.getTargetFolder()
    end

    if ~isfolder(targetFolder)
        mkdir(targetFolder);
    end

    tlcPath = fullfile(targetFolder, "piofrtos.tlc");
    tmfPath = fullfile(targetFolder, "piofrtos.tmf");
    writelines(buildSystemTargetFile(), tlcPath);
    writelines(buildTemplateMakefile(), tmfPath);

    generatedFiles = [tlcPath; tmfPath];
end

function lines = buildSystemTargetFile()
%BUILDSYSTEMTARGETFILE - Build the string lines for piofrtos.tlc.
%   Local helper for generateTargetFiles. Emits Embedded-C RT assignments,
%   codegenentry include, BEGIN_RTW_OPTIONS category and per-option blocks from
%   getOptionTable, plus rtwgensettings with BuildDirSuffix _piofrtos_rtw,
%   DerivedFrom ert.tlc, and SelectCallback piofrtos.selectCallback.
%
%   Syntax:
%       lines = buildSystemTargetFile()
%
%   Inputs:
%       none
%
%   Outputs:
%       lines - string array of TLC file contents.
%
%   Example:
%       lines = buildSystemTargetFile();
%
%   See also: GENERATETARGETFILES, BUILDRTWOPTIONBLOCK
    optionTable = piofrtos.getOptionTable();
    lines = [
        "%% SYSTLC: Arduino FreeRTOS (PlatformIO) TMF: piofrtos.tmf MAKE: make_rtw"
        "%%"
        "%% Generated by piofrtos.generateTargetFiles. Do not edit by hand."
        "%% Abstract: Embedded Coder target that builds with host-installed PlatformIO"
        "%%           and maps each discrete sample rate to a FreeRTOS task."
        "%selectfile NULL_FILE"
        ""
        "%assign CodeFormat = ""Embedded-C"""
        "%assign TargetType = ""RT"""
        "%assign Language   = ""C"""
        "%assign PreCodeGenExecCompliant = 1"
        "%assign RateBasedStepFcn = 1"
        "%assign SuppressSetEventsForThisBaseRateFcn = 1"
        "%assign SuppressMultiTaskScheduler = 1"
        "%assign AutoBuildProcedure = TLC_FALSE"
        ""
        "%include ""codegenentry.tlc"""
        ""
        "/%"
        "  BEGIN_RTW_OPTIONS"
        ""
        "  oIdx = 1;"
        "  rtwoptions(oIdx).prompt         = 'PlatformIO';"
        "  rtwoptions(oIdx).type           = 'Category';"
        "  rtwoptions(oIdx).enable         = 'on';"
        string(sprintf("  rtwoptions(oIdx).default        = %d;", numel(optionTable)))
        "  rtwoptions(oIdx).popupstrings   = '';"
        "  rtwoptions(oIdx).tlcvariable    = '';"
        "  rtwoptions(oIdx).tooltip        = '';"
        "  rtwoptions(oIdx).callback       = '';"
        "  rtwoptions(oIdx).opencallback   = '';"
        "  rtwoptions(oIdx).closecallback  = '';"
        "  rtwoptions(oIdx).makevariable   = '';"
        ""
        ];

    for optionIndex = 1:numel(optionTable)
        option = optionTable(optionIndex);
        lines = [lines; buildRtwOptionBlock(option)]; %#ok<AGROW>
    end

    lines = [lines;
        "  rtwgensettings.BuildDirSuffix = '_piofrtos_rtw';"
        "  rtwgensettings.Version        = '1';"
        "  rtwgensettings.DerivedFrom    = 'ert.tlc';"
        "  rtwgensettings.SelectCallback = 'piofrtos.selectCallback(hDlg, hSrc)';"
        ""
        "  END_RTW_OPTIONS"
        "%/"
        ];
end

function lines = buildRtwOptionBlock(option)
%BUILDRTWOPTIONBLOCK - Emit one rtwoptions assignment block for the TLC file.
%   Local helper for buildSystemTargetFile. Formats Prompt, Type, Default,
%   PopupStrings, TlcVariable, MakeVariable, Tooltip, and Callback using
%   single-quoted MATLAB string literals via toMatlabSingleQuoted.
%
%   Syntax:
%       lines = buildRtwOptionBlock(option)
%
%   Inputs:
%       option - scalar struct from getOptionTable with required fields and
%           optional PopupStrings / Callback (defaulted via getOptionField).
%
%   Outputs:
%       lines - string array ending with a blank line after the option block.
%
%   Example:
%       optionTable = piofrtos.getOptionTable();
%       lines = buildRtwOptionBlock(optionTable(1));
%
%   See also: BUILDSYSTEMTARGETFILE, GETOPTIONFIELD, TOMATLABSINGLEQUOTED
    tooltipLiteral = toMatlabSingleQuoted(option.Tooltip);
    defaultLiteral = toMatlabSingleQuoted(option.Default);
    popupLiteral = toMatlabSingleQuoted(getOptionField(option, "PopupStrings", ""));
    callbackLiteral = toMatlabSingleQuoted(getOptionField(option, "Callback", ""));

    lines = [
        "  oIdx = oIdx + 1;"
        string(sprintf("  rtwoptions(oIdx).prompt         = '%s';", option.Prompt))
        string(sprintf("  rtwoptions(oIdx).type           = '%s';", option.Type))
        "  rtwoptions(oIdx).enable         = 'on';"
        string(sprintf("  rtwoptions(oIdx).default        = %s;", defaultLiteral))
        string(sprintf("  rtwoptions(oIdx).popupstrings   = %s;", popupLiteral))
        string(sprintf("  rtwoptions(oIdx).tlcvariable    = '%s';", option.TlcVariable))
        string(sprintf("  rtwoptions(oIdx).makevariable   = '%s';", option.MakeVariable))
        string(sprintf("  rtwoptions(oIdx).tooltip        = %s;", tooltipLiteral))
        string(sprintf("  rtwoptions(oIdx).callback       = %s;", callbackLiteral))
        ""
        ];
end

function value = getOptionField(option, fieldName, defaultValue)
%GETOPTIONFIELD - Read an optional struct field or return a default.
%   Local helper for buildRtwOptionBlock when PopupStrings or Callback may be
%   absent from an option struct.
%
%   Syntax:
%       value = getOptionField(option, fieldName, defaultValue)
%
%   Inputs:
%       option - scalar struct.
%       fieldName - char/string field name to read.
%       defaultValue - value returned when the field is missing.
%
%   Outputs:
%       value - option.(fieldName) or defaultValue.
%
%   Example:
%       cb = getOptionField(option, "Callback", "");
%
%   See also: BUILDRTWOPTIONBLOCK
    if isfield(option, fieldName)
        value = option.(fieldName);
    else
        value = defaultValue;
    end
end

function literal = toMatlabSingleQuoted(value)
%TOMATLABSINGLEQUOTED - Escape a value as a MATLAB single-quoted string literal.
%   Local helper for TLC generation. Doubles embedded apostrophes then wraps
%   the string in single quotes for embedding in rtwoptions assignments.
%
%   Syntax:
%       literal = toMatlabSingleQuoted(value)
%
%   Inputs:
%       value - string or convertible text to quote.
%
%   Outputs:
%       literal - string like 'text' with internal ' escaped as ''.
%
%   Example:
%       literal = toMatlabSingleQuoted("it's");
%
%   See also: BUILDRTWOPTIONBLOCK
    escaped = replace(string(value), "'", "''");
    literal = "'" + escaped + "'";
end

function lines = buildTemplateMakefile()
%BUILDTEMPLATEMAKEFILE - Build the string lines for piofrtos.tmf.
%   Local helper for generateTargetFiles. Emits make_rtw macros, expanded
%   tokens including PIO_PLATFORM through PIO_TASK_STACK_WORDS, optional
%   include of pio_cmd.mk, and firmware/upload goals that invoke $(PIO_CMD)
%   run. Model-reference builds skip PlatformIO with an echo message.
%
%   Syntax:
%       lines = buildTemplateMakefile()
%
%   Inputs:
%       none
%
%   Outputs:
%       lines - string array of template makefile contents.
%
%   Example:
%       lines = buildTemplateMakefile();
%
%   See also: GENERATETARGETFILES, LOCATEPLATFORMIO
    lines = [
        "# Generated by piofrtos.generateTargetFiles. Do not edit by hand."
        "#"
        "# Template makefile for the Arduino FreeRTOS (PlatformIO) target."
        "# make_rtw expands tokens and then invokes MATLAB gmake, which calls"
        "# the host-installed PlatformIO CLI."
        ""
        "#------------------------ Macros read by make_rtw ------------------------------"
        "#"
        "# MAKECMD         - Command used to invoke the make utility"
        "# HOST            - PC or UNIX"
        "# BUILD           - Invoke make from the build procedure (yes/no)"
        "# SYS_TARGET_FILE - Name of system target file"
        ""
        "MAKECMD         = ""|>MATLAB_BIN<|/|>ARCH<|/gmake"""
        "HOST            = PC"
        "BUILD           = yes"
        "SYS_TARGET_FILE = piofrtos.tlc"
        "BUILD_SUCCESS   = ### Created"
        ""
        "#---------------------- Tokens expanded by make_rtw ----------------------------"
        ""
        "MODEL                   = |>MODEL_NAME<|"
        "MODULES                 = |>MODEL_MODULES<|"
        "MAKEFILE                = |>MAKEFILE_NAME<|"
        "MATLAB_ROOT             = |>MATLAB_ROOT<|"
        "ALT_MATLAB_ROOT         = |>ALT_MATLAB_ROOT<|"
        "START_DIR               = |>START_DIR<|"
        "NUMST                   = |>NUMST<|"
        "NCSTATES                = |>NCSTATES<|"
        "COMPUTER                = |>COMPUTER<|"
        "BUILDARGS               = |>BUILDARGS<|"
        "MULTITASKING            = |>MULTITASKING<|"
        "PRODUCT                 = |>PRODUCT<|"
        "MODELREF_TARGET_TYPE    = |>MODELREF_TARGET_TYPE<|"
        "RELATIVE_PATH_TO_ANCHOR = |>RELATIVE_PATH_TO_ANCHOR<|"
        "DEFINES_CUSTOM          = |>DEFINES_CUSTOM<|"
        "DEFINES_OTHER           = |>DEFINES_OTHER<|"
        "COMPILE_FLAGS_OTHER     = |>COMPILE_FLAGS_OTHER<|"
        "MODEL_HAS_DYNAMICALLY_LOADED_SFCNS = |>MODEL_HAS_DYNAMICALLY_LOADED_SFCNS<|"
        ""
        "PIO_PLATFORM            = |>PIO_PLATFORM<|"
        "PIO_BOARD               = |>PIO_BOARD<|"
        "PIO_FRAMEWORK           = |>PIO_FRAMEWORK<|"
        "PIO_MONITOR_SPEED       = |>PIO_MONITOR_SPEED<|"
        "PIO_UPLOAD              = |>PIO_UPLOAD<|"
        "PIO_TASK_STACK_WORDS    = |>PIO_TASK_STACK_WORDS<|"
        ""
        "-include pio_cmd.mk"
        "PIO_CMD ?= pio"
        ""
        "ifeq ($(MODELREF_TARGET_TYPE),NONE)"
        ""
        "ifeq ($(PIO_UPLOAD),1)"
        "ALL_GOAL = firmware upload"
        "else"
        "ifeq ($(PIO_UPLOAD),on)"
        "ALL_GOAL = firmware upload"
        "else"
        "ALL_GOAL = firmware"
        "endif"
        "endif"
        ""
        ".PHONY: all firmware upload"
        ""
        "all: $(ALL_GOAL)"
        ""
        "firmware:"
        string(sprintf("\t""$(PIO_CMD)"" run --project-dir ."))
        string(sprintf("\t@echo ### Created PlatformIO firmware for $(MODEL)"))
        ""
        "upload:"
        string(sprintf("\t""$(PIO_CMD)"" run --project-dir . -t upload"))
        string(sprintf("\t@echo ### Uploaded PlatformIO firmware for $(MODEL)"))
        ""
        "else"
        ""
        ".PHONY: all"
        ""
        "all:"
        string(sprintf("\t@echo ### Skipping PlatformIO for referenced model $(MODEL)"))
        ""
        "endif"
        ];
end
