function optionTable = getOptionTable()
%getOptionTable Return the PlatformIO rtwoptions used to generate TLC and TMF.

    targets = piofrtos.listKnownTargets();
    defaultTarget = targets(1);
    platforms = unique([targets.Platform], "stable");
    boards = unique([targets.DisplayName], "stable");
    frameworks = unique([targets.Framework], "stable");

    optionTable = struct( ...
        "Name", {"PioPlatform", "PioBoard", "PioFramework", "PioExtraLibraries", ...
        "PioMonitorSpeed", "PioUpload", "PioTaskStackWords"}, ...
        "Prompt", {"PlatformIO platform", "PlatformIO board", "PlatformIO framework", ...
        "Extra libraries", "Serial monitor speed", "Upload after build", ...
        "FreeRTOS task stack (words)"}, ...
        "Type", {"Popup", "Popup", "Popup", "Edit", "Edit", "Checkbox", "Edit"}, ...
        "Default", {defaultTarget.Platform, defaultTarget.DisplayName, defaultTarget.Framework, ...
        defaultTarget.ExtraLibraries, "115200", "off", defaultTarget.TaskStackWords}, ...
        "PopupStrings", {joinPopup(platforms), joinPopup(boards), joinPopup(frameworks), ...
        "", "", "", ""}, ...
        "Callback", {"", "piofrtos.syncKnownTarget(hDlg, hSrc)", "", "", "", "", ""}, ...
        "TlcVariable", {"PioPlatform", "PioBoard", "PioFramework", "PioExtraLibraries", ...
        "PioMonitorSpeed", "PioUpload", "PioTaskStackWords"}, ...
        "MakeVariable", {"PIO_PLATFORM", "PIO_BOARD", "PIO_FRAMEWORK", "PIO_EXTRA_LIBRARIES", ...
        "PIO_MONITOR_SPEED", "PIO_UPLOAD", "PIO_TASK_STACK_WORDS"}, ...
        "Tooltip", { ...
        "PlatformIO platform for a known-good board. Atmel AVR boards use atmelavr.", ...
        "Known-good board. Selecting a board sets platform and framework.", ...
        "PlatformIO framework. Known-good AVR boards use arduino.", ...
        "Optional PlatformIO lib_deps entries. Separate libraries with commas or semicolons. " + ...
        "AVR boards need a FreeRTOS port such as feilipu/FreeRTOS.", ...
        "Baud rate passed to PlatformIO monitor_speed and Serial.begin.", ...
        "If selected, the generated makefile runs pio run -t upload after a successful build.", ...
        "Stack depth passed to xTaskCreate for each sample-rate task. On AVR this is words."});
end

function popup = joinPopup(values)
    popup = join(values, "|");
end
