function targets = listKnownTargets()
%listKnownTargets Return PlatformIO targets known to work with this STF.

    targets = [ ...
        knownTarget("Arduino Uno", "atmelavr", "uno", "arduino")
        knownTarget("Arduino Nano", "atmelavr", "nanoatmega328", "arduino")];
end

function target = knownTarget(displayName, platform, board, framework)
    target = struct( ...
        "DisplayName", string(displayName), ...
        "Platform", string(platform), ...
        "Board", string(board), ...
        "Framework", string(framework), ...
        "ExtraLibraries", "feilipu/FreeRTOS", ...
        "TaskStackWords", "192");
end
