function addArduinoPioBoardBlocks(libName)
%ADDARDUINOPIOBOARDBLOCKS - Fill board library folders with masked System blocks.
%   Replaces the former BoardStub placeholders. Each block is a masked subsystem
%   whose dialog promotes the MATLAB System properties and whose ports are fixed
%   to the data type the driver consumes. Called from createArduinoPioLibrary.
%
%   Syntax:
%       addArduinoPioBoardBlocks(libName)
%
%   Inputs:
%       libName - (1,1) string. Library model name, usually "arduinopio_lib".
%
%   Outputs:
%       none
%
%   Example:
%       addArduinoPioBoardBlocks("arduinopio_lib");
%
%   Other m-files required: none
%   Subfunctions: addUartPorts, addWifiBlocks, addBleBlocks, addDacBlock,
%       addNativeCanBlocks, addMaskedDriver
%   MAT-files required: none
%
%   See also: CREATEARDUINOPIOLIBRARY

%   Author: Frey, Jed
%   07-Oct-2026; Last revision: 07-Oct-2026

%------------- BEGIN CODE --------------
    arguments
        libName (1,1) string
    end

    mega = libName + "/Mega 2560";
    addUartPorts(mega, "mega2560", 1);
    addMaskedDriver(mega, "Mega Analog Input", "arduinopio.blocks.common.BoardAnalogInput", 7, ...
        MaskType="Arduino PIO Mega Analog Input", ...
        Description="Mega A0-A15 as channels 0-15. Output is uint16 ADC counts. Host simulation uses SimValue.", ...
        Settings=struct("Board", "mega2560", "Pin", "0", "SimValue", "0", "SampleTime", "-1"), ...
        Promote=["Board", "Pin", "SimValue", "SampleTime"], ...
        Prompts=["Board id", "Analog channel (0 = A0)", "Simulation output (uint16)", "Sample time (-1 = inherited)"], ...
        Outputs="Counts");
    addMaskedDriver(mega, "Mega PWM", "arduinopio.blocks.common.BoardPwm", 8, ...
        MaskType="Arduino PIO Mega PWM", ...
        Description="Mega PWM pins 2-13. Input is scalar uint8 duty, 0-255.", ...
        Settings=struct("Board", "mega2560", "Pin", "2", "SampleTime", "-1"), ...
        Promote=["Board", "Pin", "SampleTime"], ...
        Prompts=["Board id", "PWM pin", "Sample time (-1 = inherited)"], ...
        Inputs="Duty", InputTypes="uint8", InputDimensions="1");

    due = libName + "/Due";
    addDacBlock(due, "due", "66", "12", 1, ...
        "Due DAC0 is pin 66 and DAC1 is pin 67. Input is scalar uint16. ResolutionBits is 12.");
    addNativeCanBlocks(due, "arduinopio.blocks.common.NativeCanTransmit", ...
        "arduinopio.blocks.common.NativeCanReceive", "due", 2);
    addUartPorts(due, "due", 4);

    mkr = libName + "/MKR WiFi 1010";
    addDacBlock(mkr, "mkrWifi1010", "15", "10", 1, ...
        "MKR A0 is digital pin 15. Input is scalar uint16. DAC resolution is 10 bits.");
    addWifiBlocks(mkr, "arduinopio.blocks.mkr.WifiTransmit", "arduinopio.blocks.mkr.WifiReceive", 2);
    addBleBlocks(mkr, "arduinopio.blocks.common.ArduinoBleTransmit", ...
        "arduinopio.blocks.common.ArduinoBleReceive", 6);

    esp = libName + "/ESP32-WROOM";
    addDacBlock(esp, "esp32Wroom", "25", "8", 1, ...
        "ESP32 DAC GPIO 25 or 26. Input is scalar uint16 and the driver writes the low 8 bits.");
    addWifiBlocks(esp, "arduinopio.blocks.common.WifiTransmit", "arduinopio.blocks.common.WifiReceive", 2);
    addBleBlocks(esp, "arduinopio.blocks.common.BleTransmit", "arduinopio.blocks.common.BleReceive", 6);
    addMaskedDriver(esp, "Touch Read", "arduinopio.blocks.common.TouchRead", 8, ...
        MaskType="Arduino PIO Touch Read", ...
        Description="ESP32 touch GPIO. Output is scalar uint16. Host simulation uses SimValue.", ...
        Settings=struct("Board", "esp32Wroom", "Pin", "4", "SimValue", "0", "SampleTime", "-1"), ...
        Promote=["Board", "Pin", "SimValue", "SampleTime"], ...
        Prompts=["Board id", "Touch GPIO", "Simulation output (uint16)", "Sample time (-1 = inherited)"], ...
        Outputs="Value");

    r4 = libName + "/Uno R4";
    addDacBlock(r4, "unoR4", "14", "12", 1, ...
        "Uno R4 A0 is digital pin 14. Input is scalar uint16. ResolutionBits is 12.");
    addNativeCanBlocks(r4, "arduinopio.blocks.unoR4.NativeCanTransmit", ...
        "arduinopio.blocks.unoR4.NativeCanReceive", "unoR4", 2);
    addMaskedDriver(r4, "LED Matrix", "arduinopio.blocks.common.LedMatrixWrite", 4, ...
        MaskType="Arduino PIO LED Matrix", ...
        Description="Uno R4 WiFi 12x8 matrix. Input is uint8(12,1). Bit 0 of each column byte is row 0.", ...
        Settings=struct("SampleTime", "-1"), ...
        Promote="SampleTime", ...
        Prompts="Sample time (-1 = inherited)", ...
        Inputs="Columns", InputTypes="uint8", InputDimensions="[12, 1]");
    addWifiBlocks(r4, "arduinopio.blocks.unoR4.WifiTransmit", "arduinopio.blocks.unoR4.WifiReceive", 5);

    ble = libName + "/Nano 33 BLE";
    addMaskedDriver(ble, "PWM Analog Output", "arduinopio.blocks.common.BoardPwm", 1, ...
        MaskType="Arduino PIO PWM Analog Output", ...
        Description="Nano 33 BLE has no DAC. Input is scalar uint8 duty, 0-255, on a PWM pin.", ...
        Settings=struct("Board", "nano33Ble", "Pin", "3", "SampleTime", "-1"), ...
        Promote=["Board", "Pin", "SampleTime"], ...
        Prompts=["Board id", "PWM pin", "Sample time (-1 = inherited)"], ...
        Inputs="Duty", InputTypes="uint8", InputDimensions="1");
    addBleBlocks(ble, "arduinopio.blocks.common.ArduinoBleTransmit", ...
        "arduinopio.blocks.common.ArduinoBleReceive", 2);
end

function addUartPorts(parent, board, firstIndex)
%ADDUARTPORTS - Add Serial 1-3 transmit and receive masks for one board.
    port = 1;
    index = firstIndex;
    while port <= 3
        settings = struct("Board", board, "Port", string(port), "BaudRate", "115200", ...
            "DataLength", "1", "SampleTime", "-1");
        promote = ["Board", "Port", "BaudRate", "DataLength", "SampleTime"];
        prompts = ["Board id", "UART port (1=Serial1, 2=Serial2, 3=Serial3)", ...
            "Baud rate", "Bytes per step (uint8)", "Sample time (-1 = inherited)"];
        description = "Input or output data is uint8 of length DataLength. Status is logical.";
        addMaskedDriver(parent, "Serial " + string(port) + " Transmit", ...
            "arduinopio.blocks.common.UartTransmit", index, ...
            MaskType="Arduino PIO UART Transmit", Description=description, ...
            Settings=settings, Promote=promote, Prompts=prompts, ...
            Inputs="Data", InputTypes="uint8", InputDimensions="1");
        addMaskedDriver(parent, "Serial " + string(port) + " Receive", ...
            "arduinopio.blocks.common.UartReceive", index + 1, ...
            MaskType="Arduino PIO UART Receive", Description=description, ...
            Settings=settings, Promote=promote, Prompts=prompts, ...
            Outputs=["Data", "Status"]);
        port = port + 1;
        index = index + 2;
    end
end

function addDacBlock(parent, board, pin, bits, index, description)
%ADDDACBLOCK - Add a uint16 DAC write mask with a board-specific default pin.
    addMaskedDriver(parent, "DAC Write", "arduinopio.blocks.common.DacWrite", index, ...
        MaskType="Arduino PIO DAC Write", Description=description, ...
        Settings=struct("Board", board, "Pin", pin, "ResolutionBits", bits, "SampleTime", "-1"), ...
        Promote=["Board", "Pin", "ResolutionBits", "SampleTime"], ...
        Prompts=["Board id", "DAC pin", "Resolution (bits)", "Sample time (-1 = inherited)"], ...
        Inputs="Code", InputTypes="uint16", InputDimensions="1");
end

function addNativeCanBlocks(parent, transmitClass, receiveClass, board, firstIndex)
%ADDNATIVECANBLOCKS - Add onboard CAN transmit and receive masks.
    transmitSettings = struct("Board", board, "Controller", "0", "BaudRateKbps", "500", ...
        "MessageId", "256", "SampleTime", "-1");
    receiveSettings = struct("Board", board, "Controller", "0", "BaudRateKbps", "500", "SampleTime", "-1");
    addMaskedDriver(parent, "Onboard CAN Transmit", transmitClass, firstIndex, ...
        MaskType="Arduino PIO Onboard CAN Transmit", ...
        Description="Input is uint8(8,1). Due has controllers 0 and 1. Uno R4 has controller 0.", ...
        Settings=transmitSettings, ...
        Promote=["Board", "Controller", "BaudRateKbps", "MessageId", "ExtendedFrame", "RemoteFrame", "SampleTime"], ...
        Prompts=["Board id", "CAN controller", "Baud rate (kbps)", "Message id", ...
            "Extended frame", "Remote frame", "Sample time (-1 = inherited)"], ...
        Inputs="Data", InputTypes="uint8", InputDimensions="[8, 1]");
    addMaskedDriver(parent, "Onboard CAN Receive", receiveClass, firstIndex + 1, ...
        MaskType="Arduino PIO Onboard CAN Receive", ...
        Description="Outputs are uint32 Id, uint8(8,1) Data, uint8 Length, and logical Status.", ...
        Settings=receiveSettings, ...
        Promote=["Board", "Controller", "BaudRateKbps", "SampleTime"], ...
        Prompts=["Board id", "CAN controller", "Baud rate (kbps)", "Sample time (-1 = inherited)"], ...
        Outputs=["Id", "Data", "Length", "Status"]);
end

function addWifiBlocks(parent, transmitClass, receiveClass, firstIndex)
%ADDWIFIBLOCKS - Add UDP and TCP transmit and receive masks.
    udpTransmit = struct("Protocol", "UDP", "Ssid", "arduino", "Password", "password", ...
        "RemoteHost", "192.168.1.20", "RemotePort", "5000", "DataLength", "1", "SampleTime", "-1");
    tcpTransmit = udpTransmit;
    tcpTransmit.Protocol = "TCP";
    udpReceive = struct("Protocol", "UDP", "Ssid", "arduino", "Password", "password", ...
        "RemoteHost", "192.168.1.20", "RemotePort", "5000", "LocalPort", "5000", ...
        "DataLength", "1", "SampleTime", "-1");
    tcpReceive = udpReceive;
    tcpReceive.Protocol = "TCP";
    transmitPromote = ["Protocol", "Ssid", "Password", "RemoteHost", "RemotePort", "DataLength", "SampleTime"];
    transmitPrompts = ["Protocol (UDP or TCP)", "SSID", "Password", "Remote host", ...
        "Remote port", "Bytes per step (uint8)", "Sample time (-1 = inherited)"];
    receivePromote = ["Protocol", "Ssid", "Password", "RemoteHost", "RemotePort", "LocalPort", "DataLength", "SampleTime"];
    receivePrompts = ["Protocol (UDP or TCP)", "SSID", "Password", "Remote host (TCP)", ...
        "Remote port (TCP)", "Local port (UDP)", "Bytes per step (uint8)", "Sample time (-1 = inherited)"];
    description = "Payload is uint8 of length DataLength. Receive status is logical and true when a byte arrives.";
    addMaskedDriver(parent, "WiFi UDP Transmit", transmitClass, firstIndex, ...
        MaskType="Arduino PIO WiFi UDP Transmit", Description=description, ...
        Settings=udpTransmit, Promote=transmitPromote, Prompts=transmitPrompts, ...
        Inputs="Data", InputTypes="uint8", InputDimensions="1");
    addMaskedDriver(parent, "WiFi UDP Receive", receiveClass, firstIndex + 1, ...
        MaskType="Arduino PIO WiFi UDP Receive", Description=description, ...
        Settings=udpReceive, Promote=receivePromote, Prompts=receivePrompts, ...
        Outputs=["Data", "Status"]);
    addMaskedDriver(parent, "WiFi TCP Transmit", transmitClass, firstIndex + 2, ...
        MaskType="Arduino PIO WiFi TCP Transmit", Description=description, ...
        Settings=tcpTransmit, Promote=transmitPromote, Prompts=transmitPrompts, ...
        Inputs="Data", InputTypes="uint8", InputDimensions="1");
    addMaskedDriver(parent, "WiFi TCP Receive", receiveClass, firstIndex + 3, ...
        MaskType="Arduino PIO WiFi TCP Receive", Description=description, ...
        Settings=tcpReceive, Promote=receivePromote, Prompts=receivePrompts, ...
        Outputs=["Data", "Status"]);
end

function addBleBlocks(parent, transmitClass, receiveClass, firstIndex)
%ADDBLEBLOCKS - Add BLE transmit and receive masks.
    settings = struct("DeviceName", "ArduinoPIO", ...
        "ServiceUuid", "19B10000-E8F2-537E-4F6C-D104768A1214", ...
        "CharacteristicUuid", "19B10001-E8F2-537E-4F6C-D104768A1214", ...
        "DataLength", "1", "SampleTime", "-1");
    promote = ["DeviceName", "ServiceUuid", "CharacteristicUuid", "DataLength", "SampleTime"];
    prompts = ["Device name", "Service UUID", "Characteristic UUID", ...
        "Bytes per step (uint8, 1-20)", "Sample time (-1 = inherited)"];
    description = "Payload is uint8 of length DataLength, at most 20 bytes. Receive status is logical.";
    addMaskedDriver(parent, "BLE Transmit", transmitClass, firstIndex, ...
        MaskType="Arduino PIO BLE Transmit", Description=description, ...
        Settings=settings, Promote=promote, Prompts=prompts, ...
        Inputs="Data", InputTypes="uint8", InputDimensions="1");
    addMaskedDriver(parent, "BLE Receive", receiveClass, firstIndex + 1, ...
        MaskType="Arduino PIO BLE Receive", Description=description, ...
        Settings=settings, Promote=promote, Prompts=prompts, ...
        Outputs=["Data", "Status"]);
end

function addMaskedDriver(parent, name, className, index, options)
%ADDMASKEDDRIVER - Place a masked subsystem around one MATLAB System driver.
    arguments
        parent (1,1) string
        name (1,1) string
        className (1,1) string
        index (1,1) double {mustBeInteger, mustBePositive}
        options.MaskType (1,1) string
        options.Description (1,1) string
        options.Settings struct = struct()
        options.Promote (1,:) string = string.empty(1, 0)
        options.Prompts (1,:) string = string.empty(1, 0)
        options.Inputs (1,:) string = string.empty(1, 0)
        options.InputTypes (1,:) string = string.empty(1, 0)
        options.InputDimensions (1,:) string = string.empty(1, 0)
        options.Outputs (1,:) string = string.empty(1, 0)
    end

    if numel(options.Promote) ~= numel(options.Prompts)
        error("arduinopio:MaskPromptCount", ...
            "Block %s promote names and prompts must be the same length.", name);
    end

    dest = parent + "/" + name;
    col = mod(index - 1, 4);
    row = floor((index - 1) / 4);
    x = 40 + col * 160;
    y = 40 + row * 100;
    add_block("built-in/Subsystem", dest, Position=[x, y, x + 130, y + 70]);
    innerBlocks = find_system(dest, LookUnderMasks="all", SearchDepth=1, Type="Block");
    for innerIndex = 1:numel(innerBlocks)
        blockPath = string(innerBlocks{innerIndex});
        if blockPath ~= dest
            delete_block(blockPath);
        end
    end

    driver = dest + "/Driver";
    add_block("simulink/User-Defined Functions/MATLAB System", driver, ...
        Position=[140, 40, 300, 140]);
    set_param(driver, "System", className);
    settingNames = string(fieldnames(options.Settings));
    if ~isempty(settingNames)
        settingArgs = cell(1, 2 * numel(settingNames));
        for settingIndex = 1:numel(settingNames)
            settingName = settingNames(settingIndex);
            settingArgs{2 * settingIndex - 1} = char(settingName);
            settingArgs{2 * settingIndex} = char(options.Settings.(settingName));
        end
        set_param(driver, settingArgs{:});
    end

    for inputIndex = 1:numel(options.Inputs)
        inName = options.Inputs(inputIndex);
        add_block("simulink/Sources/In1", dest + "/" + inName, ...
            Position=[20, 30 + (inputIndex - 1) * 40, 50, 44 + (inputIndex - 1) * 40]);
        set_param(dest + "/" + inName, "OutDataTypeStr", options.InputTypes(inputIndex));
        set_param(dest + "/" + inName, "PortDimensions", options.InputDimensions(inputIndex));
        add_line(dest, inName + "/1", "Driver/" + string(inputIndex));
    end

    for outputIndex = 1:numel(options.Outputs)
        outName = options.Outputs(outputIndex);
        add_block("simulink/Sinks/Out1", dest + "/" + outName, ...
            Position=[360, 30 + (outputIndex - 1) * 40, 390, 44 + (outputIndex - 1) * 40]);
        add_line(dest, "Driver/" + string(outputIndex), outName + "/1");
    end

    if any(options.Promote == "Pin")
        displayCommand = arduinopio.maskDisplayWithPin(name);
    elseif any(options.Promote == "Port")
        displayCommand = arduinopio.maskDisplayWithPin(name, Expression="Port", Label="Port");
    elseif any(options.Promote == "Controller")
        displayCommand = arduinopio.maskDisplayWithPin(name, Expression="Controller", Label="CAN");
    else
        displayCommand = "disp('" + name + "')";
    end

    mask = Simulink.Mask.create(dest);
    mask.Type = options.MaskType;
    mask.Description = options.Description;
    mask.Display = displayCommand;
    for promoteIndex = 1:numel(options.Promote)
        propertyName = options.Promote(promoteIndex);
        mask.addParameter(Type="promote", TypeOptions={"Driver/" + propertyName}, ...
            Name=propertyName, Prompt=options.Prompts(promoteIndex));
    end
end
