function makeInfo = rtwmakecfg()
%rtwmakecfg Add Arduino PIO driver sources used by the I/O S-functions.
    rootDir = arduinopio.getRootFolder();
    srcDir = fullfile(rootDir, "src", "drivers");
    makeInfo.includePath = {char(srcDir)};
    makeInfo.sourcePath = {char(srcDir)};
    makeInfo.sources = { ...
        "arduinopio_lock.cpp", ...
        "arduinopio_gpio.cpp", ...
        "arduinopio_adc.cpp", ...
        "arduinopio_pwm.cpp", ...
        "arduinopio_uart.cpp", ...
        "arduinopio_extint.cpp", ...
        "arduinopio_hwint_avr.cpp"};
    makeInfo.linkLibsObjs = {};
end
